# Generated by Django 4.0.4 on 2022-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyapp', '0005_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='body3',
            field=models.TextField(blank=True),
        ),
    ]
