# Generated by Django 4.0.4 on 2022-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyapp', '0006_topic_body1_topic_body2_topic_body3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politic',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='entertainment',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='latest',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='latest',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='latest',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metro',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metro',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metro',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='politic',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='politic',
            name='body3',
            field=models.TextField(blank=True),
        ),
    ]
